### List all employees
GET http://localhost:8080/api/employees/
Accept: application/json

### Find employee by id
GET http://localhost:8080/api/employees/2
Accept: application/json

### Not found
GET http://localhost:8080/api/employees/5
Accept: application/json

### Create employee
POST http://localhost:8080/api/employees/
Content-Type: application/json

{
"name": "John Smith"
}

### Create employee (invalid)
POST http://localhost:8080/api/employees/
Content-Type: application/json

{
  "name": "Aaaaaaaaaaaaaa"
}

### Update
PUT http://localhost:8080/api/employees/5
Content-Type: application/json

{
  "name": "Jack Jack Doe"
}

### Delete
DELETE http://localhost:8080/api/employees/1

### Not found
GET http://localhost:8080/api